### PR TITLE
Collaboration on Selection/Delete Tools

### PR DESCRIPTION
**Pull request by fgdrf**
Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

### CODE REVIEW

**Comment by fgdrf** [comment]
Hi @nprigour,
added few commits to your branch, hope commit messages will guide you a bit. Here is the list of changes:
 * added link to general tool preferences page (for delete and selection tool)
 * selection radius config on selection preferences page
 * fixed prefs link in editor for selection and delete tool(s) (from map editor)
 * tool uses correct prefs while config changed in between (by user) and tool is still active
 * unified pref constants and added javadoc
 * delete confirmation dialog uses attribute value over ID

During tests of deletion tool I got the following execptions I guess you fixed with [pull 228](https://github.com/locationtech/udig-platform/pull/228). Is it possible that the branch is not branched from latest master. On my local branch where I contribute from the commit 9c2982d9106c2404b3fb8258776e896ededb79ed wasn't on it.

`
!ENTRY org.locationtech.udig.project 1 0 2017-08-13 20:46:10.964
!MESSAGE Layer transaction already set null
!STACK 0
java.lang.IllegalStateException: Layer transaction already set null
	at org.locationtech.udig.project.internal.impl.UDIGSimpleFeatureStore.setTransactionInternal(UDIGSimpleFeatureStore.java:211)
	at org.locationtech.udig.project.internal.impl.UDIGSimpleFeatureStore.removeFeatures(UDIGSimpleFeatureStore.java:94)
	at org.locationtech.udig.project.internal.commands.edit.DeleteFeatureCommand.execute(DeleteFeatureCommand.java:71)
	at org.locationtech.udig.project.command.CommandManager$Executor.execute(CommandManager.java:395)
	at org.locationtech.udig.project.command.CommandManager$Executor.run(CommandManager.java:326)
	at org.locationtech.udig.project.command.CommandManager$Executor.run(CommandManager.java:312)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)`

**Comment by nprigour** [comment]
Hi @fgdrf,

A concern regarding your last bullet 

- delete confirmation dialog uses attribute value over ID

I think using always the fid is far more convenient since the atribute value is not guarantee to be unique. I.e. in an application that I have developed there is often the case that we have overlapping features which are duplicates and we want to keep only one o them. This means that all of their attributes are the same and it can be distinguished only by their fid which will always be unique. If we display the attribute value then it will be really difficult to choose which one to delete.

**Comment by fgdrf** [comment]
@nprigour Interesting.I thought because the user selected a feature which is displayed with preferred attribute it might be a good point to show the same attribute value in the confirmation dialog. 

In addition I assume that users do not really work with ID's and decide on attributes which have a semantic, don't they?

What do you think about having the following aproach:
* if the user has a prefered attribut configured and the value of the feature isn't null, it's displayed right before the Identfied in braces : `Question <attribute-value> (featureId)`
* otherwise only the featureId is displayed like before?

**Comment by nprigour** [comment]
that would be the best approach I think.

**Comment by fgdrf** [comment]
@nprigour, whenever you like merge it, please use the squash option. Then we get all my commits as a single commit onto your Branch. anything else I should change before? Thanks in advance!

**Comment by nprigour** [comment]
Hi @fgdrf,
Trying to check out, compile and test this pull request contribution resulted in compilation error. It seems that
class org.locationtech.udig.tool.select.preferences.SelectionToolPreferencePage does not exist. Checking your commits I see that you have changed the package where SelectionToolPreferencePage was (initially located at org.locationtech.udig.tool.select.internal).
Since this is actually a file remove and recreation, is it possible that you forget to add the new file to the git index and thus it is not yet committed?

**Comment by fgdrf** [comment]
Oh, sorry for this, I guess I missed to add the moved file(s). Going to add `org.locationtech.udig.tool.select.preferences.SelectionToolPreferenceInitializer` as well.

**Comment by nprigour** [comment]
@fgdrf there are still some compile errors
File org.locationtech.udig.tool.select.commands.SetAOILayerCommand still uses the old import
`import org.locationtech.udig.tool.select.internal.SelectionToolPreferencePage;`
Please fix it.

Moreover I would suggest the following improvement in org.locationtech.udig.tools.edit.impl.DeleteTool class (line 209). Change
`final Object attribValue = (attribName != null ? feature.getAttribute(attribName) : feature.getIdentifier());`
to 
`final Object attribValue = (attribName != null ? feature.getAttribute(attribName) : null);`
in order to avoid duplication of feature.getIdentifier() display in the confirmation message that follows in the case attribName is not present

**Comment by nprigour** [comment]
Hi @fgdrf ,

Running the application I got the following warnings:

> Warning: NLS missing message: Feature_Selection_Radius in: org.locationtech.udig.project.ui.internal.messages
> Warning: NLS missing message: Feature_Selection_Radius_tooltip in: org.locationtech.udig.project.ui.internal.messages
> Warning: NLS missing message: PREFERENCES_LINK_TO_GENERAL_PAGE in: org.locationtech.udig.tools.internal.messages

Probably resulted from the rearrangement of preferences in different plugins.
The first two concerning Feature_Selection_Radius.. I assume they can be removed since I can see you have moved them in org.locationtech.udig.tool.select plugin.
The latter one (PREFERENCES_LINK_TO_GENERAL_PAGE) has been introduced during this pull request both in **org.locationtech.udig.project.ui.internal.Messages**  & **org.locationtech.udig.tools.internal.messages** but only the former is used. 

Can you check and clear out the code before I proceed with accepting the contribution

**Comment by fgdrf** [comment]
Sure, good findings again! Going to fix it.

Anyway, IMHO the plugin structure and dependencies in between are a bit
strange but I'd address a refactoring in another pull request later. You
are welcome to collaborate ;)

**Comment by nprigour** [comment]
So @fgdrf now in order to accept your pull request do you suggest to use the "squash and merge" online option provided in githhub or we will have a similar problem with sign-off as some week ago?

**Comment by fgdrf** [comment]
I assume squashing is fine since all commits have signed-off-by hint. Lets try the github option, maybe it makes sense to cleanup the commit messages in the dialog - your choise. Many Thanks

**Pull request merged**
